config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  resources :endereco_funcionarios
  resources :funcionarios
  resources :setors
  resources :endereco_empresas
  resources :empresas
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/setor.rb
class Setor < ApplicationRecord
    has_many :funcionario, dependent: :destroy
    validates :nome, presence:true
end

app/controllers/setors_controller.rb
class SetorsController < ApplicationController
  before_action :set_setor, only: %i[ show edit update destroy ]

  # GET /setors or /setors.json
  def index
    @setors = Setor.all
  end

  # GET /setors/1 or /setors/1.json
  def show
  end

  # GET /setors/new
  def new
    @setor = Setor.new
  end

  # GET /setors/1/edit
  def edit
  end

  # POST /setors or /setors.json
  def create
    @setor = Setor.new(setor_params)

    respond_to do |format|
      if @setor.save
        format.html { redirect_to setor_url(@setor), notice: "Setor criado com sucesso." }
        format.json { render :show, status: :created, location: @setor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @setor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /setors/1 or /setors/1.json
  def update
    respond_to do |format|
      if @setor.update(setor_params)
        format.html { redirect_to setor_url(@setor), notice: "Setor editado com sucesso." }
        format.json { render :show, status: :ok, location: @setor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @setor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /setors/1 or /setors/1.json
  def destroy
    @setor.destroy

    respond_to do |format|
      format.html { redirect_to setors_url, notice: "Setor apagado com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setor
      @setor = Setor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def setor_params
      params.require(:setor).permit(:nome)
    end
end

app/helpers/setors_helper.rb
module SetorsHelper
end

app/views/setors/_form.html.erb
<%= form_with(model: setor) do |form| %>
  <% if setor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(setor.errors.count, "error") %> prohibited this setor from being saved:</h2>

      <ul>
        <% setor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div id="CRUDs">
      <button class="btn btn-primary" type="submit">Criar Setor</button>
  </div>
<% end %>

app/views/setors/_formEditar.html.erb
<%= form_with(model: setor) do |form| %>
<section class="forms">
  <h1>Editar Setor</h1>
  <div class="field">
    <%= form.label :nome %>
  </div>
    <%= form.text_field :nome %>

  <div id="CRUDs">
    <button class="btn btn-primary" type="submit">Atualizar Setor</button>
  </div>
  <% if setor.errors.any? %>
    <div>
      <h2><%= pluralize(setor.errors.count, "error") %>. Não é possível salvar esse funcionário.<br> Confirá os campos<h2>
  <% end %>
<% end %>
  <%= link_to "Voltar", setors_path, class: 'btn btn-primary' %>
</section>

app/views/setors/_setor.html.erb
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Setor</title>
</head>
<body>
  
  <div id="<%= dom_id setor %>">
 
    <p>
      <strong>Nome:</strong>
      <%= setor.nome %>
    </p>

  </div>
</body>
</html>

app/views/setors/edit.html.erb
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="application.css">
  <title>Setor</title>
</head>
<body>
    <%= render 'formEditar', setor: @setor %>


</body>
</html>

app/views/setors/index.html.erb
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Setores</title>
</head>
<body>

  <div id="notice">
    <%= notice %>
  </div>

  <div class="index">
    <h1>Setores</h1>
    <% @setors.each do |setor| %>
      <%= render setor %>
      <%= link_to "Detalhes", setor, class:'btn btn-primary' %>
      <hr>
    <% end %>
    <%= link_to "Voltar Home", home_index_path, class: 'btn btn-primary' %>
    <%= link_to "Novo Setor", new_setor_path, class: 'btn btn-primary' %>

  </div>

</body>
</html>

app/views/setors/new.html.erb
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="application.css">
  <title>Setores</title>
</head>
<body>
  
  <section class="forms">
    <h1>Novo Setor</h1>

    <%= render "form", setor: @setor %>
    <%= link_to "Voltar", setors_path, class: 'btn btn-primary' %>
  </section>
  


</body>
</html>

app/views/setors/show.html.erb
<div id="notice">
  <%= notice %>
</div>

<section class="index" id="detalhes">
  <%= render @setor %>
<div id="CRUDs">
  <%= button_to "Apagar Setor", @setor, method: :delete, class: "btn btn-primary" %>
</div>
  
  <%= link_to "Voltar", setors_path, class: 'btn btn-primary' %>
  <%= link_to "Editar Setor", edit_setor_path(@setor), class: 'btn btn-primary' %>
</section>