config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  resources :endereco_funcionarios
  resources :funcionarios
  resources :setors
  resources :endereco_empresas
  resources :empresas
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_cabecalho.html.erb
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="application">
</head>
<body>
    <header>
        <nav>   
            <%= link_to "Home", home_index_path %>
            <%= link_to "Empresas", empresas_path %>
            <%= link_to "Funcionários", funcionarios_path %>
            <%= link_to "Setores", setors_path %>
        </nav>
        
    </header>    
</body>
</html>

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Recursos Humanos</title>
  <link rel="stylesheet" href="application.css">
</head>
<body>
    <main>
        <section>
            <h1>Recursos Humanos</h1>
            <h2>Sobre:</h2>
            <p>Bem-Vindo! Meu nome é Gustavo Orpinelli de Marco e estou no 4° período de Ciências da Computação na UNESP - Rio Claro.
            Nesse projeto, desenvolvi uma aplicação prática utilizando o framework Ruby on Rails, BootStrap e banco de dados SQL. Meu principal objetivo ao criar essa aplicação é demonstrar minhas habilidades e conhecimentos afim de adquirir experiência no desenvolvimento de aplicações web .</p>
            <p>A ideia ao criar esse site, foi combinar meus conhecimentos em Ruby on Rails com minha experiência de trabalho em um escritório de contabilidade e recursos humanos. O intuito foi desenvolver uma aplicação responsiva que simplificasse o cadastro de empresas e seus funcionários, permitindo agilizar o processo de criação, busca, atualização e exclusão de informações. </p>
            <p>Espero que essa aplicação demonstre meu comprometimento em criar soluções eficientes e de qualidade. Caso queira saber mais sobre o projeto, explorar suas funcionalidades ou discutir o processo de desenvolvimento, sinta-se à vontade para explorar o restante do site e entrar em contato comigo.</p>
            <aside>
                <h3>Contatos:</h3>
                <ul>
                    <li><strong>Email: </strong> <a href="mailto:gustavoorpinelli99@gmail.com">gustavoorpinelli99@gmail.com</a> / <a href="mailto:gustavo.marco@unesp.br">gustavo.marco@unesp.br</a> </li>
                    <li><strong>Telefone: </strong>(19)99482-9669 / (19)3542-3958</li>
                    <li><strong>GitHub: </strong><a href="https://github.com/GustavoDMarco" target="_blank">github.com/GustavoDMarco</a></li>
                    <li><strong>Linkedin: </strong><a href="https://www.linkedin.com/in/gustavo-orpinelli"
                    target="_blank">linkedin.com/in/gustavo-orpinelli-de-marco</a></li>
                </ul>
            </aside>
        </section>
    </main>
</body>
</html>