config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  resources :endereco_funcionarios
  resources :funcionarios
  resources :setors
  resources :endereco_empresas
  resources :empresas
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/empresa.rb
class Empresa < ApplicationRecord
    has_one :endereco_empresa, :dependent => :destroy
    has_many :funcionario, dependent: :destroy
    accepts_nested_attributes_for :endereco_empresa, reject_if: :all_blank
    validates :nome, :cnpj, :email, :tel, :endereco_empresa, presence: true
end

app/controllers/empresas_controller.rb
class EmpresasController < ApplicationController
  before_action :set_empresa, only: %i[ show edit update destroy ]

  # GET /empresas or /empresas.json
  def index
    @empresas = Empresa.all
    @empresas = Empresa.paginate(page: params[:page], per_page: 3)
  end

  # GET /empresas/1 or /empresas/1.json
  def show
  end

  # GET /empresas/new
  def new
    @empresa = Empresa.new
    @empresa.build_endereco_empresa
  end

  # GET /empresas/1/edit
  def edit
  end

  # POST /empresas or /empresas.json
  def create
    @empresa = Empresa.new(empresa_params)

    respond_to do |format|
      if @empresa.save
        format.html { redirect_to empresa_url(@empresa), notice: "Empresa criada com sucesso." }
        format.json { render :show, status: :created, location: @empresa }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /empresas/1 or /empresas/1.json
  def update
    respond_to do |format|
      if @empresa.update(empresa_params)
        format.html { redirect_to empresa_url(@empresa), notice: "Empresa editada com sucesso." }
        format.json { render :show, status: :ok, location: @empresa }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empresas/1 or /empresas/1.json
  def destroy
    @empresa.destroy

    respond_to do |format|
      format.html { redirect_to empresas_url, notice: "Empresa apagada com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_empresa
      @empresa = Empresa.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def empresa_params
      params.require(:empresa).permit(:nome, :cnpj, :email, :tel, endereco_empresa_attributes: [:rua, :num, :bairro, :cidade, :estado])
    end
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/views/empresas/_dadosempresa.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Empresa</title>
</head>
<body>
  <div id="<%= dom_id empresa %>">
    <section class="index" id="detalhes">
      <h2>Dados:</h2>
      <p>
        <strong>Nome:</strong>
        <%= empresa.nome %>
      </p>
    
      <p>
        <strong>Cnpj:</strong>
        <%= empresa.cnpj %>
      </p>
      <h2>Contato:</h2>
      <p>
        <strong>Email:</strong>
        <%= empresa.email %>
      </p>
    
      <p>
        <strong>Tel:</strong>
        <%= empresa.tel %>
      </p>
      <h2>Endereço:</h2>
      <p>
        <strong>Rua:</strong>
        <%= empresa.endereco_empresa.rua %>
      </p>
    
      <p>
        <strong>Num:</strong>
        <%= empresa.endereco_empresa.num %>
      </p>
    
      <p>
        <strong>Bairro:</strong>
        <%= empresa.endereco_empresa.bairro %>
      </p>
    
      <p>
        <strong>Cidade:</strong>
        <%= empresa.endereco_empresa.cidade %>
      </p>
    
      <p>
        <strong>Estado:</strong>
        <%= empresa.endereco_empresa.estado %>
      </p>
    
    <div id="CRUDs">
      <%= button_to "Apagar Empresa", @empresa, method: :delete, class: "btn btn-primary" %>
    </div>
      <%= link_to "Voltar", empresas_path, class: 'btn btn-primary' %>
      <%= link_to "Editar Empresa", edit_empresa_path(@empresa), class: 'btn btn-primary' %>
    </section>
    
  </div>

</body>
</html>

app/views/empresas/_empresa.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Empresas</title>
</head>
<body>
  <div id="<%= dom_id empresa %>">
    <p>
      <strong>Nome:</strong>
      <%= empresa.nome %>
    </p>
  
    <p>
      <strong>Cnpj:</strong>
      <%= empresa.cnpj %>
    </p>
  
    <p>
      <strong>Email:</strong>
      <%= empresa.email %>
    </p>
  
    <p>
      <strong>Tel:</strong>
      <%= empresa.tel %>
    </p>
  
    <p>
      <strong>Rua:</strong>
      <%= empresa.endereco_empresa.rua %>
    </p>
  
  </div>
</body>
</html>

app/views/empresas/_form.html.erb
<%= form_with(model: empresa) do |form| %>
<section class="forms">
  <h1>Nova Empresa</h1>

  <h2 id="CampoDados">Dados:</h2>
  <div class='field'>
    <%= form.label :nome%>
  </div>
    <%= form.text_field :nome %>

  <div class='field'>
    <%= form.label :cnpj%>
  </div>
    <%= form.text_field :cnpj %>
    <hr>
  <h2 id="Campos">Contatos:</h2>
  <div class='field'>
    <%= form.label :email%>
  </div>
    <%= form.text_field :email %>

  <div class='field'>
    <%= form.label :tel%>
  </div>
    <%= form.text_field :tel %>
    <hr>

  <%=form.fields_for :endereco_empresa do |endereco_fields|%>
  <h2 id="Campos">Endereço:</h2>
    <div class='field'>
      <%= form.label :rua%>
    </div>
      <%= endereco_fields.text_field :rua %>

    <div class='field'>
      <%= form.label :num%>
    </div>
      <%= endereco_fields.number_field :num %>

    <div class='field'>
      <%= form.label :bairro%>
    </div>
      <%= endereco_fields.text_field :bairro %>

    <div class='field'>
      <%= form.label :cidade%>
    </div>
      <%= endereco_fields.text_field :cidade %>

    <div class='field'>
      <%= form.label :estado%>
    </div>
      <%= endereco_fields.text_field :estado %>
  <% end%>

  <div id="CRUDs">
    <button class="btn btn-primary" type="submit">Criar Empresa</button>
  </div>
<% end %>

  <% if empresa.errors.any? %>
    <div>
      <h2><%= pluralize(empresa.errors.count, "Erros") %>. Não é possível salvar esse funcionário.<br> Confirá os campos<h2>
    </div>
  <% end %>
    <%= link_to "Voltar", empresas_path, class: 'btn btn-primary' %>
   </section>

app/views/empresas/_formEditar.html.erb
<%= form_with(model: empresa) do |form| %>
<section class="forms">
  <h1>Editar Empresa</h1>

  <h2 id="CampoDados">Dados:</h2>
  <div class='field'>
    <%= form.label :nome%>
  </div>
    <%= form.text_field :nome %>

  <div class='field'>
    <%= form.label :cnpj%>
  </div>
    <%= form.text_field :cnpj %>
    <hr>
  <h2 id="Campos">Contatos:</h2>
  <div class='field'>
    <%= form.label :email%>
  </div>
    <%= form.text_field :email %>

  <div class='field'>
    <%= form.label :tel%>
  </div>
    <%= form.text_field :tel %>
    <hr>

  <%=form.fields_for :endereco_empresa do |endereco_fields|%>
  <h2 id="Campos">Endereço:</h2>
    <div class='field'>
      <%= form.label :rua%>
    </div>
      <%= endereco_fields.text_field :rua %>

    <div class='field'>
      <%= form.label :num%>
    </div>
      <%= endereco_fields.number_field :num %>

    <div class='field'>
      <%= form.label :bairro%>
    </div>
      <%= endereco_fields.text_field :bairro %>

    <div class='field'>
      <%= form.label :cidade%>
    </div>
      <%= endereco_fields.text_field :cidade %>

    <div class='field'>
      <%= form.label :estado%>
    </div>
      <%= endereco_fields.text_field :estado %>
  <% end%>

  <div id="CRUDs">
    <button class="btn btn-primary" type="submit">Atualizar Empresa</button>
  </div>
<% end %>

  <% if empresa.errors.any? %>
    <div>
      <h2><%= pluralize(empresa.errors.count, "Erros") %>. Não é possível salvar esse funcionário.<br> Confirá os campos<h2>
    </div>
  <% end %>
    <%= link_to "Voltar", empresas_path, class: 'btn btn-primary' %>
   </section>

app/views/empresas/edit.html.erb
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="application.css">
  <title>Empresas</title>
</head>
<body>

  <%= render "formEditar", empresa: @empresa %>

  
</body>
</html>

app/views/empresas/index.html.erb
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Empresas</title>
  <link rel="stylesheet" href="application.css">
</head>
<body>
  <div id="notice">
    <%= notice %>
  </div>


  <div class="index">
    <h1>Empresas</h1>
    <% @empresas.each do |empresa| %>
      <%= render empresa %>
      <%= link_to "Detalhes", empresa, class:'btn btn-primary' %>
      <hr>
    <% end %>
    <div id="Paginacao">
      <%= will_paginate @empresas %>
    </div>
    
      <%= link_to "Voltar Home", home_index_path, class: 'btn btn-primary' %>
      <%= link_to "Nova Empresa", new_empresa_path, class: 'btn btn-primary' %>
  </div>
    
</body>
</html>

app/views/empresas/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="application.css">
  <title>Empresa</title>
</head>
<body>
  
  <%= render "form", empresa: @empresa %>


</body>
</html>

app/views/empresas/show.html.erb
<div id="notice">
  <%= notice %>
</div>
<%= render partial: "dadosempresa", locals:{empresa: @empresa} %>