config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  resources :endereco_funcionarios
  resources :funcionarios
  resources :setors
  resources :endereco_empresas
  resources :empresas
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/funcionario.rb
class Funcionario < ApplicationRecord
  belongs_to :empresa
  belongs_to :setor
  has_one :endereco_funcionario, :dependent => :destroy
  accepts_nested_attributes_for :endereco_funcionario, reject_if: :all_blank
  attr_accessor :rua, :num, :bairro, :cidade, :estado

  validates :nome, :cpf,:idade, :email, :tel, :salario, :admissao, :endereco_funcionario, presence: true
end

app/controllers/funcionarios_controller.rb
class FuncionariosController < ApplicationController
  before_action :set_funcionario, only: %i[ show edit update destroy ]
  
  # GET /funcionarios or /funcionarios.json
  def index
    @funcionarios = Funcionario.all
    @funcionarios= Funcionario.paginate(page: params[:page], per_page: 3)
  end
  
  # GET /funcionarios/1 or /funcionarios/1.json
  def show
  end
  
  # GET /funcionarios/new
  def new
    @funcionario = Funcionario.new
    @funcionario.build_endereco_funcionario
  
  end
  
  # GET /funcionarios/1/edit
  def edit
  end
  
  # POST /funcionarios or /funcionarios.json
  def create
    @funcionario = Funcionario.new(funcionario_params)
  
    respond_to do |format|
      if @funcionario.save
        format.html { redirect_to funcionario_url(@funcionario), notice: "Funcionário criado com sucesso" }
        format.json { render :show, status: :created, location: @funcionario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PATCH/PUT /funcionarios/1 or /funcionarios/1.json
  def update
    respond_to do |format|
      if @funcionario.update(funcionario_params)
        format.html { redirect_to funcionario_url(@funcionario), notice: "Funcionário editado com sucesso." }
        format.json { render :show, status: :ok, location: @funcionario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /funcionarios/1 or /funcionarios/1.json
  def destroy
    @funcionario.destroy
  
    respond_to do |format|
      format.html { redirect_to funcionarios_url, notice: "Funcionário apagado com sucesso." }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funcionario
      @funcionario = Funcionario.find(params[:id])
    end
  
    # Only allow a list of trusted parameters through.
    def funcionario_params
      params.require(:funcionario).permit(:nome, :cpf, :idade, :email, :tel, :empresa_id, :setor_id, :admissao, :salario,endereco_funcionario_attributes: [:rua, :num, :bairro, :cidade, :estado, :funcionario_id])
    end
  end
  

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

app/views/funcionarios/_dados.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Funcionário</title>
</head>
<body>
  <div id="<%= dom_id funcionario %>">
    <section class="index" id="detalhes">
      <h2>Dados:</h2>
        <p>
          <strong>Nome:</strong>
          <%= funcionario.nome %>
        </p>
  
        <p>
          <strong>Cpf:</strong>
          <%= funcionario.cpf %>
        </p>
  
        <p>
          <strong>Idade:</strong>
          <%= funcionario.idade %>
        </p>
  
        <p>
          <strong>Empresa:</strong>
          <%= funcionario.empresa.nome %>
        </p>
  
        <p>
          <strong>Admissão:</strong>
          <%= l funcionario.admissao, format: :default %>
        </p>
  
        <p>
          <strong>Salário:</strong>
          <%= funcionario.salario %>
        </p>
  
        <p>
          <strong>Setor:</strong>
          <%= funcionario.setor.nome %>
        </p>
  
        <h2>Contato:</h2>
        <p>
          <strong>Email:</strong>
          <%= funcionario.email %>
        </p>
  
        <p>
          <strong>Tel:</strong>
          <%= funcionario.tel %>
        </p>
  
        <h2>Endereço:</h2>
        <p>
          <strong>Num:</strong>
          <%= funcionario.endereco_funcionario.num%>
        </p>
  
        <p>
          <strong>Bairro:</strong>
          <%= funcionario.endereco_funcionario.bairro%>
        </p>
  
        <p>
          <strong>Cidade:</strong>
          <%= funcionario.endereco_funcionario.cidade%>
        </p>
  
        <p>
          <strong>Estado:</strong>
          <%= funcionario.endereco_funcionario.estado%>
        </p>
        <div id="CRUDs">
          <%= button_to "Apagar funcionário", @funcionario, method: :delete, class: "btn btn-primary" %>
        </div>
        <%= link_to "Voltar", funcionarios_path, class: 'btn btn-primary' %>
        <%= link_to "Editar funcionário", edit_funcionario_path(@funcionario), class: 'btn btn-primary' %>
      </section>
  </div>
  
 

app/views/funcionarios/_form.html.erb
  <%= form_with(model: funcionario) do |form| %>
    <section class="forms">
      <h1>Novo Funcionário</h1>

      <h2 id="CampoDados">Dados:</h2>
      <div class="field">
        <%= form.label :nome %>
      </div>
        <%= form.text_field :nome %>

      <div class="field">
        <%= form.label :cpf %>
      </div>
        <%= form.text_field :cpf %>

      <div class="field">
        <%= form.label :idade %>
      </div>
        <%= form.number_field :idade %>

      <div class="field">
        <%= form.label :empresa_id %>
      </div>
        <%= collection_select(:funcionario,:empresa_id, Empresa.all, :id, :nome)%>

      <div class="field">
        <%= form.label :admissao %>
      </div>
        <%= form.date_field :admissao%>

        <div class="field">
        <%= form.label :salario %>
      </div>
        <%= form.text_field :salario %>


      <div class="field">
        <%= form.label :setor_id %>
      </div>
        <%= collection_select(:funcionario, :setor_id, Setor.all, :id, :nome) %>

        <hr>

        <h2 id="Campos">Contatos:</h2>
      <div class="field">
        <%= form.label :email %>
      </div>
        <%= form.text_field :email %>

      <div class="field">
        <%= form.label :tel %>
      </div>
        <%= form.text_field :tel %>

      <hr> 
    
      <%= form.fields_for :endereco_funcionario do |endereco_fields| %>
            <h2 id="Campos">Endereço:</h2>
          <div class="field">
            <%= form.label :rua %>
          </div>
            <%= endereco_fields.text_field :rua %>
        
          <div class="field">
            <%= form.label :num %>
          </div>
            <%= endereco_fields.text_field :num %>
        
          <div class="field">
            <%= form.label :bairro %>
          </div>
            <%= endereco_fields.text_field :bairro %>
        
          <div class="field">
            <%= form.label :cidade %>
          </div>
            <%= endereco_fields.text_field :cidade %>
        
          <div class="field">
            <%= form.label :estado %>
          </div>
            <%= endereco_fields.text_field :estado %>
          </div>
      <% end %>
        <div id="CRUDs">
          <button class="btn btn-primary" type="submit">Criar Funcionário</button>
        </div>
<% end %>
    <% if funcionario.errors.any? %>
      <div>
        <h2><%= pluralize(funcionario.errors.count, "Erros") %>. Não é possível salvar esse funcionário.<br> Confirá os campos</h2>
      </div>
    <% end %>
  <%= link_to "Voltar", funcionarios_path, class: 'btn btn-primary' %>
    </section>

app/views/funcionarios/_formEditar.html.erb
<%= form_with(model: funcionario) do |form| %>
  <section class="forms">
    <h1>Editar Funcionário</h1>
    
    <h2 id="CampoDados">Dados:</h2>
    <div class="field">
      <%= form.label :nome %>
    </div>
      <%= form.text_field :nome %>

    <div class="field">
      <%= form.label :cpf %>
    </div>
      <%= form.text_field :cpf %>

    <div class="field">
      <%= form.label :idade %>
    </div>
      <%= form.number_field :idade %>

    <div class="field">
      <%= form.label :empresa_id %>
    </div>
      <%= collection_select(:funcionario,:empresa_id, Empresa.all, :id, :nome)%>

    <div class="field">
      <%= form.label :admissao %>
    </div>
      <%= form.date_field :admissao %>

      <div class="field">
      <%= form.label :salario %>
    </div>
      <%= form.text_field :salario %>


    <div class="field">
      <%= form.label :setor_id %>
    </div>
      <%= collection_select(:funcionario, :setor_id, Setor.all, :id, :nome) %>

      <hr>

      <h2 id="Campos">Contatos:</h2>
    <div class="field">
      <%= form.label :email %>
    </div>
      <%= form.text_field :email %>

    <div class="field">
      <%= form.label :tel %>
    </div>
      <%= form.text_field :tel %>

    <hr> 
  
    <%= form.fields_for :endereco_funcionario do |endereco_fields| %>
          <h2 id="Campos">Endereço:</h2>
        <div class="field">
          <%= form.label :rua %>
        </div>
          <%= endereco_fields.text_field :rua %>
      
        <div class="field">
          <%= form.label :num %>
        </div>
          <%= endereco_fields.text_field :num %>
      
        <div class="field">
          <%= form.label :bairro %>
        </div>
          <%= endereco_fields.text_field :bairro %>
      
        <div class="field">
          <%= form.label :cidade %>
        </div>
          <%= endereco_fields.text_field :cidade %>
      
        <div class="field">
          <%= form.label :estado %>
        </div>
          <%= endereco_fields.text_field :estado %>
        </div>
      <% end %>
      <div id="CRUDs">
        <button class="btn btn-primary" type="submit">Atualizar Funcionário</button>
      </div>
<% end %>

          <% if funcionario.errors.any? %>
      <div>
        <h2><%= pluralize(funcionario.errors.count, "Erros") %>. Não é possível salvar esse funcionário.<br> Confirá os campos</h2>
      </div>
    <% end %>

    <%= link_to "Voltar", funcionarios_path, class: 'btn btn-primary' %>
  </section>

app/views/funcionarios/_funcionario.html.erb
<div id="<%= dom_id funcionario %>">
  <p>
    <strong>Nome:</strong>
    <%= funcionario.nome %>
  </p>

  <p>
    <strong>Cpf:</strong>
    <%= funcionario.cpf %>
  </p>

  <p>
    <strong>Idade:</strong>
    <%= funcionario.idade %>
  </p>

  <p>
    <strong>Admissão:</strong>
    <%= l funcionario.admissao, format: :default %>
  </p>

  <p>
    <strong>Salário:</strong>
    <%= funcionario.salario %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= funcionario.email %>
  </p>

  <p>
    <strong>Tel:</strong>
    <%= funcionario.tel %>
  </p>

  <p>
    <strong>Rua:</strong>
    <%= funcionario.endereco_funcionario.rua%>
  </p>

  <p>
    <strong>Empresa:</strong>
    <%= funcionario.empresa.nome %>
  </p>

  <p>
    <strong>Setor:</strong>
    <%= funcionario.setor.nome %>
  </p>


</div>

app/views/funcionarios/edit.html.erb
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="application.css">
  <title>Funcionários</title>
</head>
<body>
  
  <%= render "formEditar", funcionario: @funcionario %>
</body>
</html>

app/views/funcionarios/index.html.erb
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Funcionários</title>
</head>
<body>
  <div id="notice">
    <%= notice %>
  </div>

  <div class="index">
    <h1>Funcionários</h1>
    <% @funcionarios.each do |funcionario| %>
      <%= render funcionario %>
      <%= link_to "Detalhes", funcionario, class:'btn btn-primary' %>
      <hr>
    <% end %>
    <div id="Paginacao">
      <%= will_paginate @funcionarios %>
    </div>
    <%= link_to "Voltar Home", home_index_path, class: 'btn btn-primary' %>
    <%= link_to "Novo Funcionário", new_funcionario_path, class: 'btn btn-primary' %>
  </div>
</body>
</html>

app/views/funcionarios/new.html.erb
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="application.css">
  <title>Funcionário</title>
</head>
<body>
    <%= render "form", funcionario: @funcionario %>

</body>
</html>

app/views/funcionarios/show.html.erb
<div id="notice">
  <%= notice %>
</div>

<%= render partial: "dados", locals: { funcionario: @funcionario }%>

</div>